cmsRun fitMuon.py nJet0 tightiso tightid data_all data_2017 pt default
cmsRun fitMuon.py nJet0 tightiso tightid mc_all mc_2017 pt default
cmsRun fitMuon.py nJet1 tightiso tightid data_all data_2017 pt default
cmsRun fitMuon.py nJet1 tightiso tightid mc_all mc_2017 pt default
cmsRun fitMuon.py nJet2 tightiso tightid data_all data_2017 pt default
cmsRun fitMuon.py nJet2 tightiso tightid mc_all mc_2017 pt default
cmsRun fitMuon.py nJet3 tightiso tightid data_all data_2017 pt default
cmsRun fitMuon.py nJet3 tightiso tightid mc_all mc_2017 pt default
cmsRun fitMuon.py nJet4 tightiso tightid data_all data_2017 pt default
cmsRun fitMuon.py nJet4 tightiso tightid mc_all mc_2017 pt default
cmsRun fitMuon.py nJet4more tightiso tightid data_all data_2017 pt default
cmsRun fitMuon.py nJet4more tightiso tightid mc_all mc_2017 pt default
cmsRun fitMuon.py nJet5more tightiso tightid data_all data_2017 pt default
cmsRun fitMuon.py nJet5more tightiso tightid mc_all mc_2017 pt default

cmsRun fitMuon.py nJet0 tightiso tightid data_all data_2017 eta default
cmsRun fitMuon.py nJet0 tightiso tightid mc_all mc_2017 eta default
cmsRun fitMuon.py nJet1 tightiso tightid data_all data_2017 eta default
cmsRun fitMuon.py nJet1 tightiso tightid mc_all mc_2017 eta default
cmsRun fitMuon.py nJet2 tightiso tightid data_all data_2017 eta default
cmsRun fitMuon.py nJet2 tightiso tightid mc_all mc_2017 eta default
cmsRun fitMuon.py nJet3 tightiso tightid data_all data_2017 eta default
cmsRun fitMuon.py nJet3 tightiso tightid mc_all mc_2017 eta default
cmsRun fitMuon.py nJet4 tightiso tightid data_all data_2017 eta default
cmsRun fitMuon.py nJet4 tightiso tightid mc_all mc_2017 eta default
cmsRun fitMuon.py nJet4more tightiso tightid data_all data_2017 eta default
cmsRun fitMuon.py nJet4more tightiso tightid mc_all mc_2017 eta default
cmsRun fitMuon.py nJet5more tightiso tightid data_all data_2017 eta default
cmsRun fitMuon.py nJet5more tightiso tightid mc_all mc_2017 eta default
